---
tasks:
  warming:
  branch_freshness:
  buildifier:
  gazelle:
  test:
    targets:
      - //...
    flags:
      - --nocheck_visibility
      - --test_output=summary
      - --remote_download_minimal
